spring.application.name=${SPRING_APP_NAME:springsecsection1}
spring.security.user.name=${SECURITY_USERNAME:eazybytes}
spring.security.user.password=${SECURITY_PASSWORD:12345}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}


#############################################################################################################################################################

The ${SECURITY_PASSWORD:12345} is a Spring Boot property placeholder that reads an environment variable or system property named SECURITY_PASSWORD. 
Here's what it means:

SECURITY_PASSWORD: This is the name of the environment variable (or system property) that Spring will try to read.

12345: This is the default value that will be used if SECURITY_PASSWORD is not set in the environment or system properties.

